-- Equipment Data (20 items)
INSERT INTO items (custom_id, name, category, total_stock, type, is_active) VALUES
('EQ-001', 'MacBook Pro 14"', 'Laptop', 5, 'EQUIPMENT', true),
('EQ-002', 'Dell XPS 15', 'Laptop', 5, 'EQUIPMENT', true),
('EQ-003', 'Epson Projector', 'Projector', 3, 'EQUIPMENT', true),
('EQ-004', 'HDMI Cable 2m', 'Cable', 20, 'EQUIPMENT', true),
('EQ-005', 'Sony A7 Camera', 'Camera', 2, 'EQUIPMENT', true),
('EQ-006', 'Tripod', 'Accessory', 5, 'EQUIPMENT', true),
('EQ-007', 'iPad Pro 12.9"', 'Tablet', 4, 'EQUIPMENT', true),
('EQ-008', 'Wireless Mouse', 'Accessory', 10, 'EQUIPMENT', true),
('EQ-009', 'Mechanical Keyboard', 'Accessory', 5, 'EQUIPMENT', true),
('EQ-010', '27" 4K Monitor', 'Monitor', 6, 'EQUIPMENT', true),
('EQ-011', 'USB-C Hub', 'Accessory', 15, 'EQUIPMENT', true),
('EQ-012', 'Laser Pointer', 'Presenter', 8, 'EQUIPMENT', true),
('EQ-013', 'Extension Cord', 'Power', 10, 'EQUIPMENT', true),
('EQ-014', 'Voice Recorder', 'Audio', 3, 'EQUIPMENT', true),
('EQ-015', 'GoPro Hero 10', 'Camera', 2, 'EQUIPMENT', true),
('EQ-016', 'Key Light', 'Lighting', 4, 'EQUIPMENT', true),
('EQ-017', 'Green Screen', 'Studio', 1, 'EQUIPMENT', true),
('EQ-018', 'VR Headset', 'VR', 2, 'EQUIPMENT', true),
('EQ-019', 'Webcam 1080p', 'Camera', 10, 'EQUIPMENT', true),
('EQ-020', 'Portable Speaker', 'Audio', 3, 'EQUIPMENT', true);

-- Consumables Data (20 items)
INSERT INTO items (custom_id, name, category, total_stock, type, is_active) VALUES
('CS-001', 'A4 Paper (Ream)', 'Paper', 50, 'CONSUMABLE', true),
('CS-002', 'Ballpoint Pen (Blue)', 'Stationery', 100, 'CONSUMABLE', true),
('CS-003', 'Ballpoint Pen (Black)', 'Stationery', 100, 'CONSUMABLE', true),
('CS-004', 'Whiteboard Marker (Black)', 'Stationery', 30, 'CONSUMABLE', true),
('CS-005', 'Whiteboard Marker (Red)', 'Stationery', 30, 'CONSUMABLE', true),
('CS-006', 'Whiteboard Marker (Blue)', 'Stationery', 30, 'CONSUMABLE', true),
('CS-007', 'Stapler', 'Stationery', 10, 'CONSUMABLE', true),
('CS-008', 'Staples (Box)', 'Stationery', 50, 'CONSUMABLE', true),
('CS-009', 'Tape (Roll)', 'Stationery', 20, 'CONSUMABLE', true),
('CS-010', 'Post-it Notes (Yellow)', 'Stationery', 40, 'CONSUMABLE', true),
('CS-011', 'Paper Clips (Box)', 'Stationery', 30, 'CONSUMABLE', true),
('CS-012', 'Binder Clips (Medium)', 'Stationery', 20, 'CONSUMABLE', true),
('CS-013', 'AA Batteries (Pack of 4)', 'Electronics', 25, 'CONSUMABLE', true),
('CS-014', 'AAA Batteries (Pack of 4)', 'Electronics', 25, 'CONSUMABLE', true),
('CS-015', 'Masking Tape', 'Stationery', 10, 'CONSUMABLE', true),
('CS-016', 'Glue Stick', 'Stationery', 15, 'CONSUMABLE', true),
('CS-017', 'Scissors', 'Stationery', 5, 'CONSUMABLE', true),
('CS-018', 'Correction Tape', 'Stationery', 20, 'CONSUMABLE', true),
('CS-019', 'Highlighter (Yellow)', 'Stationery', 25, 'CONSUMABLE', true),
('CS-020', 'Envelope (A4)', 'Stationery', 50, 'CONSUMABLE', true);
